on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3 # Updated to the latest version

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3 # Updated to the latest version
        with:
          node-version: 20 # Specify Node.js version 20

      - name: Install dependencies
        run: npm install    

      - name: Test
        run: npm test
        env:
          CI: true

      - name: Generate build
        run: npm run build

      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v3 # Updated to the latest version
        with:
          name: react-github-actions-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3 # Updated to the latest version
        with:
          name: react-github-actions-build

      # Set the credentials from repository settings/secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2 # Updated to the latest version
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # Copy the files from build folder to the S3 bucket
      - name: Deploy to S3
        run: aws s3 sync . s3://react-github-actions --acl public-read
        working-directory: react-github-actions-build

  release:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v3 # Updated to the latest version
        with:
          name: react-github-actions-build

      # Zip the build using external action
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: react-github-actions-release-build.zip
          path: react-github-actions-build

      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v3 # Updated to the latest version
        with:
          name: react-github-actions-release-build.zip
          path: react-github-actions-release-build.zip

      # Make official GitHub release which will trigger sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: react-github-actions-release-build.zip
          body: https://react-github-actions.s3.amazonaws.com/index.html
          token: ${{ secrets.GITHUB_TOKEN }}
